version: '2'
services:
    analise-app:
        image: analise
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://analise-postgresql:5432/analise
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    analise-postgresql:
        extends:
            file: postgresql.yml
            service: analise-postgresql
